---
title: "scRNAseq induced neurons"
author: "Joachim"
date: "December 22, 2017"
output: 
  html_document: 
    theme: cerulean
    toc: yes
---

##########################################################
################         LIBRARIES        ################
##########################################################

```{r LOAD LIBRARIES, warning=FALSE, message=FALSE}

pacman::p_load(rio, tidyverse, reshape, RColorBrewer, readxl, edgeR)

```

##########################################################
################      CUSTOM FUNCTIONS    ################
##########################################################

```{r CUSTOM FUNCTIONS, warning=FALSE, message=FALSE}
#--------------------------Read data------------------------------
readat <- function(id) {
  pid = paste0("C:/Users/joachim/Desktop/Projects/scRNAseq.iN/Figure.Data/Figure.S1/", id)
  dat = import(pid)
  dat = dat %>% remove_rownames %>% column_to_rownames(var = names(dat)[1])
}

readex <- function(id, sheet) {
  pid = paste0("C:/Users/joachim/Desktop/Projects/scRNAseq.iN/Figure.Data/Figure.S1/", id)
  dat = read_excel(pid, sheet = sheet)
}

#----------------------------Theme1--------------------------------
theme_jo <- function(base_size = 12){
  theme_classic(base_size = base_size) +
    theme(
      legend.key = element_blank(), 
      strip.background = element_blank(),
      strip.text = element_text(size = 20, color = "grey10"),
      plot.title = element_blank(), 
      axis.title = element_text(size = 30, color = "grey10"), 
      axis.text = element_text(size = 25, color = "grey10"), 
      legend.title = element_blank(), 
      legend.text = element_blank(),
      axis.line = element_line(size = 1.1, color = "grey10"),
      axis.ticks = element_line(size = 1.1, color = "grey10"),
      axis.ticks.length = unit(0.3, "cm"),
      legend.position = "none")
}

#----------------------------Theme2--------------------------------
theme_blank = function(base_size = 12){
  theme_jo(base_size = base_size) +
    theme(
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.background = element_blank(),
      strip.text = element_blank()
    )
}
```

##########################################################
#################        FIGURE S1A       ################
##########################################################

```{r FIGURE S1A, warning=FALSE, message=FALSE}
#----------------------------FigureS1A--------------------------------
#read data
read.list = list()
for (i in 1:4) {
  read.list[[i]] = readex("ips.to.neuron.xlsx", i)}
dat.ips = read.list[[1]] %>%
  column_to_rownames(var = "Gene") %>%
  as.data.frame()
dat.nervous = read.list[[2]]
dat.cand = read.list[[3]] %>%
  mutate(p.Gene = paste0("p1@", .$Gene))
dat.tf = read.list[[4]]

#define groups and subset data
group = dat.ips %>% colnames %>% stringr::str_split("_") %>% sapply(., function(X) X[3]) %>% .[1:12]
f.data = dat.ips[rowSums(dat.ips)>5, 1:12]

#combine data and group; Calculate dispersions; Fit dispersion
my.data = f.data %>% DGEList(counts = ., group = group) %>% estimateCommonDisp %>% estimateTagwiseDisp
design = model.matrix(~group)
colnames(design) = unique(group)
fit = glmFit(my.data, design)

#ANOVA-like analysis
lrt = glmLRT(fit, coef = 2:4)
lrt$table$FDR = p.adjust(lrt$table$PValue, method = "BH")
de.table = lrt$table

#set a cutoff, add day0
sig.data = de.table %>%
  rownames_to_column %>%
  filter(FDR <= 0.05) %>% 
  select(1:4) %>% 
  setNames(gsub("logFC.", "", names(.))) %>% 
  mutate(day00 = 0) %>% 
  column_to_rownames(var = "rowname") %>%
  select("day00", "day06", "day12", "day18") %>%
  t %>% 
  as.data.frame

#select TFs
tfs = dat.tf %>% 
  mutate(p.Gene = paste0("p1@", .$Gene))
sig.data.tf = sig.data[, which(colnames(sig.data) %in% tfs$p.Gene)] %>%
  t %>% 
  melt %>% 
  full_join(dat.cand, by = c("X1" = "p.Gene")) %>% 
  select(c("X1", "X2", "value", "Color"))
sig.data.tf = sig.data.tf[-(which(is.na(sig.data.tf$value) == "TRUE")), ]
sig.data.tf[is.na(sig.data.tf)] = "Z"

#create color palette
my.pal.ips = c("Z" = "grey90", "A" = "#1b75bb", "B" = "#f6b520", "C" = "#bf282c", "D" = "#545453")

#ploy data
ggplot(sig.data.tf, aes(X2, value, group = X1, color = as.factor(Color), fill = as.factor(Color))) +
  geom_line(alpha = 0.5, lwd = 1, lineend = "round") +
  geom_point(data = sig.data.tf[-(which(sig.data.tf$Color == "Z")), ], size = 4, pch = 19) +
  geom_point(data = sig.data.tf[-(which(sig.data.tf$Color == "Z")), ], size = 2, pch = 19, color = "white") +
  geom_line(data = sig.data.tf[-(which(sig.data.tf$Color == "Z")), ], lwd = 1, lineend = "round") +
  scale_color_manual(values = my.pal.ips) +
  scale_fill_manual(values = my.pal.ips) +
  scale_x_discrete(expand = c(0.1, 0.1), labels = c("Day0", "Day6", "Day12", "Day18")) +
  labs(x = "Time-point", y = "Log2(FC vs. Day0)") +
  geom_hline(aes(yintercept = 0), color = "grey20", lty = 2, size = 1) +
  theme_jo() +
  theme(legend.position = "none")
```

##########################################################
#################        FIGURE S1C       ################
##########################################################

```{r  FIGURE S1C, warning=FALSE, message=FALSE}
#----------------------------FigureS1C--------------------------------
freq <- function(frame){
  mat = matrix(ncol = 1,nrow = 0)
  for (i in 1:length(row.names(frame))){
    x = data.frame(V1 = rep(frame[i, 1], times = frame[i, 2]))
    mat = rbind(mat, x)}
  return(mat)
}

#run model
my.per = c(3, 5, 7)

final.frame = matrix(nrow = 0, ncol = 2)
for (j in 1:length(my.per)) {
  #create list
  my.list = list()  
  for(l in seq_len(1000)) {
  mat = matrix(data = 0, nrow = 20, ncol = 1000)
  colnames(mat) = paste0("Cell", 1:1000)
  row.names(mat) = paste0("TF", 1:20)
  for (i in seq_len(20)){
    mat[i, ][sample(1000, 1000/my.per[j])] = 1
    }
  x = colSums(mat)
  my.list[[l]] = as.data.frame(table(x))
}

#create data frame for plotting
my.frame = my.list %>% 
  do.call("rbind", .) %>% 
  split(.$x) %>% 
  lapply(function(X) mean(X$Freq)) %>% 
  unlist %>% 
  as.data.frame %>%
  rename(replace = c("." = "Freq")) %>%
  rownames_to_column(var = "TF")
my.freq = freq(my.frame) %>%
  mutate(Group = LETTERS[j])

final.frame = rbind(final.frame, my.freq)

}

my.pal = c("A" = "#535353", "B" = "#C0292C", "C" = "grey70")

ggplot(final.frame, aes(x=V1, group = Group, fill = Group, color = Group)) +
  geom_density(bw = 1, alpha = 0.4) +
  #scale_x_discrete(breaks = c(0, 5, 10, 15, 20)) +
  scale_color_manual(values = my.pal) +
  scale_fill_manual(values = my.pal) +
  theme_jo()


```